#FROM tensorflow/tensorflow:2.1.2-gpu

FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
RUN apt-get update && apt-get install -y python3.7-dev python3-pip git gcc

RUN mkdir /workspace
WORKDIR /workspace

COPY requirements.txt .

RUN python3.7 -m pip install -U pip setuptools
RUN python3.7 -m pip install -r requirements.txt

RUN pip install git+https://github.com/SKT-AI/KoGPT2#egg=kogpt2

COPY . .

CMD python3.7 app.py